services:
  mma-g2-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mmag2
      POSTGRES_USER: mmag2_root
      POSTGRES_DB: mmmag234!

