spring.application.name=maturity-models-assessments-g2-api

spring.datasource.url=jdbc:postgresql://localhost:5432/mma_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
